### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Foggalong** [0xAether/pipes#1]
On the off chance you see this, do you know the original creator for this script? We're trying to find out what license should be applied to [this modification](https://github.com/pipeseroni/pipes.sh/tree/master) of the script. The earliest we've found reference to a similar script is [here](https://bbs.archlinux.org/viewtopic.php?pid=728932#p728932) but that is as far as we've gotten. I hope you can help us out!

**Comment by 0xAether** [comment]
@Foggalong First off sorry about the huge delay. In all honesty I know as much as you do of the origin of this script. A few years ago someone posted this script on 4chan.org/g and it didn't work in anything other than OSX. Since I don't run that garbage, I wanted to get it running on Debian (Squeeze at the time if I'm not remembering incorrectly). So I changed somethings, mainly the UTF-8 box characters. I might have changed some other things as well although I can't remember. This script I wish to license under the GNU General Public License version 3.

**Comment by Foggalong** [comment]
Hey @0xAether, thanks for the reply! In the end I actually managed to [find the original author](https://github.com/pipeseroni/pipes.sh/issues/13#issuecomment-108126757) and contact them - the gist of their response was that the project is Public Domain and that derivative works can use whatever license they want :)
